name: Terraform CI/CD

on:
  #pull_request:
  #  branches:
  #    - main
  push:
    branches:
      - infra

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6
        
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      # if: github.event_name == 'push'
      run: 
        echo "Running Terraform Plan..."
        terraform plan -no-color > plan.txt 2>&1
        echo "Plan completed. Contents saved to plan.txt"
        echo "--- Plan Output Preview ---"
        head -20 plan.txt
        echo "--- End Preview ---"

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
